/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LegendsRouteImport } from './routes/legends'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PedidoTokenRouteImport } from './routes/pedido.$token'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as AuthenticatedProdutorRouteImport } from './routes/_authenticated/produtor'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedAfiliadosRouteImport } from './routes/_authenticated/afiliados'
import { Route as AuthenticatedAdmRouteImport } from './routes/_authenticated/adm'
import { Route as AuthenticatedProdutorIndexRouteImport } from './routes/_authenticated/produtor.index'
import { Route as AuthenticatedMembrosIndexRouteImport } from './routes/_authenticated/membros.index'
import { Route as AuthenticatedAdmIndexRouteImport } from './routes/_authenticated/adm.index'
import { Route as AuthenticatedProdutorSaquesRouteImport } from './routes/_authenticated/produtor.saques'
import { Route as AuthenticatedProdutorProdutosRouteImport } from './routes/_authenticated/produtor.produtos'
import { Route as AuthenticatedProdutorNovoRouteImport } from './routes/_authenticated/produtor.novo'
import { Route as AuthenticatedProdutorIntegracoesRouteImport } from './routes/_authenticated/produtor.integracoes'
import { Route as AuthenticatedProdutorFunilRouteImport } from './routes/_authenticated/produtor.funil'
import { Route as AuthenticatedProdutorFinanceiroRouteImport } from './routes/_authenticated/produtor.financeiro'
import { Route as AuthenticatedProdutorConquistasRouteImport } from './routes/_authenticated/produtor.conquistas'
import { Route as AuthenticatedMembrosSlugRouteImport } from './routes/_authenticated/membros.$slug'
import { Route as AuthenticatedAdmUsuariosRouteImport } from './routes/_authenticated/adm.usuarios'
import { Route as AuthenticatedAdmSaquesRouteImport } from './routes/_authenticated/adm.saques'
import { Route as AuthenticatedAdmRelatoriosRouteImport } from './routes/_authenticated/adm.relatorios'
import { Route as AuthenticatedAdmProdutosRouteImport } from './routes/_authenticated/adm.produtos'
import { Route as AuthenticatedAdmLogsRouteImport } from './routes/_authenticated/adm.logs'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicWebhooksMulticaixaRouteImport } from './routes/api/public/webhooks/multicaixa'
import { Route as AuthenticatedProdutorSucessoIdRouteImport } from './routes/_authenticated/produtor.sucesso.$id'
import { Route as AuthenticatedProdutorEditarIdRouteImport } from './routes/_authenticated/produtor.editar.$id'
import { Route as AuthenticatedProdutorCursoIdRouteImport } from './routes/_authenticated/produtor.curso.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LegendsRoute = LegendsRouteImport.update({
  id: '/legends',
  path: '/legends',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoTokenRoute = PedidoTokenRouteImport.update({
  id: '/pedido/$token',
  path: '/pedido/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProdutorRoute = AuthenticatedProdutorRouteImport.update({
  id: '/produtor',
  path: '/produtor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAfiliadosRoute = AuthenticatedAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdmRoute = AuthenticatedAdmRouteImport.update({
  id: '/adm',
  path: '/adm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutorIndexRoute =
  AuthenticatedProdutorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedMembrosIndexRoute =
  AuthenticatedMembrosIndexRouteImport.update({
    id: '/membros/',
    path: '/membros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdmIndexRoute = AuthenticatedAdmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdmRoute,
} as any)
const AuthenticatedProdutorSaquesRoute =
  AuthenticatedProdutorSaquesRouteImport.update({
    id: '/saques',
    path: '/saques',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedProdutorProdutosRoute =
  AuthenticatedProdutorProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedProdutorNovoRoute =
  AuthenticatedProdutorNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedProdutorIntegracoesRoute =
  AuthenticatedProdutorIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedProdutorFunilRoute =
  AuthenticatedProdutorFunilRouteImport.update({
    id: '/funil',
    path: '/funil',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedProdutorFinanceiroRoute =
  AuthenticatedProdutorFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedProdutorConquistasRoute =
  AuthenticatedProdutorConquistasRouteImport.update({
    id: '/conquistas',
    path: '/conquistas',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedMembrosSlugRoute =
  AuthenticatedMembrosSlugRouteImport.update({
    id: '/membros/$slug',
    path: '/membros/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdmUsuariosRoute =
  AuthenticatedAdmUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdmRoute,
  } as any)
const AuthenticatedAdmSaquesRoute = AuthenticatedAdmSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => AuthenticatedAdmRoute,
} as any)
const AuthenticatedAdmRelatoriosRoute =
  AuthenticatedAdmRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdmRoute,
  } as any)
const AuthenticatedAdmProdutosRoute =
  AuthenticatedAdmProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdmRoute,
  } as any)
const AuthenticatedAdmLogsRoute = AuthenticatedAdmLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdmRoute,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMulticaixaRoute =
  ApiPublicWebhooksMulticaixaRouteImport.update({
    id: '/api/public/webhooks/multicaixa',
    path: '/api/public/webhooks/multicaixa',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProdutorSucessoIdRoute =
  AuthenticatedProdutorSucessoIdRouteImport.update({
    id: '/sucesso/$id',
    path: '/sucesso/$id',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedProdutorEditarIdRoute =
  AuthenticatedProdutorEditarIdRouteImport.update({
    id: '/editar/$id',
    path: '/editar/$id',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedProdutorCursoIdRoute =
  AuthenticatedProdutorCursoIdRouteImport.update({
    id: '/curso/$id',
    path: '/curso/$id',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contactos': typeof ContactosRoute
  '/faq': typeof FaqRoute
  '/legends': typeof LegendsRoute
  '/loja': typeof LojaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/adm': typeof AuthenticatedAdmRouteWithChildren
  '/afiliados': typeof AuthenticatedAfiliadosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/produtor': typeof AuthenticatedProdutorRouteWithChildren
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/adm/logs': typeof AuthenticatedAdmLogsRoute
  '/adm/produtos': typeof AuthenticatedAdmProdutosRoute
  '/adm/relatorios': typeof AuthenticatedAdmRelatoriosRoute
  '/adm/saques': typeof AuthenticatedAdmSaquesRoute
  '/adm/usuarios': typeof AuthenticatedAdmUsuariosRoute
  '/membros/$slug': typeof AuthenticatedMembrosSlugRoute
  '/produtor/conquistas': typeof AuthenticatedProdutorConquistasRoute
  '/produtor/financeiro': typeof AuthenticatedProdutorFinanceiroRoute
  '/produtor/funil': typeof AuthenticatedProdutorFunilRoute
  '/produtor/integracoes': typeof AuthenticatedProdutorIntegracoesRoute
  '/produtor/novo': typeof AuthenticatedProdutorNovoRoute
  '/produtor/produtos': typeof AuthenticatedProdutorProdutosRoute
  '/produtor/saques': typeof AuthenticatedProdutorSaquesRoute
  '/adm/': typeof AuthenticatedAdmIndexRoute
  '/membros/': typeof AuthenticatedMembrosIndexRoute
  '/produtor/': typeof AuthenticatedProdutorIndexRoute
  '/produtor/curso/$id': typeof AuthenticatedProdutorCursoIdRoute
  '/produtor/editar/$id': typeof AuthenticatedProdutorEditarIdRoute
  '/produtor/sucesso/$id': typeof AuthenticatedProdutorSucessoIdRoute
  '/api/public/webhooks/multicaixa': typeof ApiPublicWebhooksMulticaixaRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contactos': typeof ContactosRoute
  '/faq': typeof FaqRoute
  '/legends': typeof LegendsRoute
  '/loja': typeof LojaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/afiliados': typeof AuthenticatedAfiliadosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/adm/logs': typeof AuthenticatedAdmLogsRoute
  '/adm/produtos': typeof AuthenticatedAdmProdutosRoute
  '/adm/relatorios': typeof AuthenticatedAdmRelatoriosRoute
  '/adm/saques': typeof AuthenticatedAdmSaquesRoute
  '/adm/usuarios': typeof AuthenticatedAdmUsuariosRoute
  '/membros/$slug': typeof AuthenticatedMembrosSlugRoute
  '/produtor/conquistas': typeof AuthenticatedProdutorConquistasRoute
  '/produtor/financeiro': typeof AuthenticatedProdutorFinanceiroRoute
  '/produtor/funil': typeof AuthenticatedProdutorFunilRoute
  '/produtor/integracoes': typeof AuthenticatedProdutorIntegracoesRoute
  '/produtor/novo': typeof AuthenticatedProdutorNovoRoute
  '/produtor/produtos': typeof AuthenticatedProdutorProdutosRoute
  '/produtor/saques': typeof AuthenticatedProdutorSaquesRoute
  '/adm': typeof AuthenticatedAdmIndexRoute
  '/membros': typeof AuthenticatedMembrosIndexRoute
  '/produtor': typeof AuthenticatedProdutorIndexRoute
  '/produtor/curso/$id': typeof AuthenticatedProdutorCursoIdRoute
  '/produtor/editar/$id': typeof AuthenticatedProdutorEditarIdRoute
  '/produtor/sucesso/$id': typeof AuthenticatedProdutorSucessoIdRoute
  '/api/public/webhooks/multicaixa': typeof ApiPublicWebhooksMulticaixaRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contactos': typeof ContactosRoute
  '/faq': typeof FaqRoute
  '/legends': typeof LegendsRoute
  '/loja': typeof LojaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/adm': typeof AuthenticatedAdmRouteWithChildren
  '/_authenticated/afiliados': typeof AuthenticatedAfiliadosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/produtor': typeof AuthenticatedProdutorRouteWithChildren
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/adm/logs': typeof AuthenticatedAdmLogsRoute
  '/_authenticated/adm/produtos': typeof AuthenticatedAdmProdutosRoute
  '/_authenticated/adm/relatorios': typeof AuthenticatedAdmRelatoriosRoute
  '/_authenticated/adm/saques': typeof AuthenticatedAdmSaquesRoute
  '/_authenticated/adm/usuarios': typeof AuthenticatedAdmUsuariosRoute
  '/_authenticated/membros/$slug': typeof AuthenticatedMembrosSlugRoute
  '/_authenticated/produtor/conquistas': typeof AuthenticatedProdutorConquistasRoute
  '/_authenticated/produtor/financeiro': typeof AuthenticatedProdutorFinanceiroRoute
  '/_authenticated/produtor/funil': typeof AuthenticatedProdutorFunilRoute
  '/_authenticated/produtor/integracoes': typeof AuthenticatedProdutorIntegracoesRoute
  '/_authenticated/produtor/novo': typeof AuthenticatedProdutorNovoRoute
  '/_authenticated/produtor/produtos': typeof AuthenticatedProdutorProdutosRoute
  '/_authenticated/produtor/saques': typeof AuthenticatedProdutorSaquesRoute
  '/_authenticated/adm/': typeof AuthenticatedAdmIndexRoute
  '/_authenticated/membros/': typeof AuthenticatedMembrosIndexRoute
  '/_authenticated/produtor/': typeof AuthenticatedProdutorIndexRoute
  '/_authenticated/produtor/curso/$id': typeof AuthenticatedProdutorCursoIdRoute
  '/_authenticated/produtor/editar/$id': typeof AuthenticatedProdutorEditarIdRoute
  '/_authenticated/produtor/sucesso/$id': typeof AuthenticatedProdutorSucessoIdRoute
  '/api/public/webhooks/multicaixa': typeof ApiPublicWebhooksMulticaixaRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contactos'
    | '/faq'
    | '/legends'
    | '/loja'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/adm'
    | '/afiliados'
    | '/perfil'
    | '/produtor'
    | '/checkout/$slug'
    | '/p/$slug'
    | '/pedido/$token'
    | '/produto/$slug'
    | '/adm/logs'
    | '/adm/produtos'
    | '/adm/relatorios'
    | '/adm/saques'
    | '/adm/usuarios'
    | '/membros/$slug'
    | '/produtor/conquistas'
    | '/produtor/financeiro'
    | '/produtor/funil'
    | '/produtor/integracoes'
    | '/produtor/novo'
    | '/produtor/produtos'
    | '/produtor/saques'
    | '/adm/'
    | '/membros/'
    | '/produtor/'
    | '/produtor/curso/$id'
    | '/produtor/editar/$id'
    | '/produtor/sucesso/$id'
    | '/api/public/webhooks/multicaixa'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contactos'
    | '/faq'
    | '/legends'
    | '/loja'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/afiliados'
    | '/perfil'
    | '/checkout/$slug'
    | '/p/$slug'
    | '/pedido/$token'
    | '/produto/$slug'
    | '/adm/logs'
    | '/adm/produtos'
    | '/adm/relatorios'
    | '/adm/saques'
    | '/adm/usuarios'
    | '/membros/$slug'
    | '/produtor/conquistas'
    | '/produtor/financeiro'
    | '/produtor/funil'
    | '/produtor/integracoes'
    | '/produtor/novo'
    | '/produtor/produtos'
    | '/produtor/saques'
    | '/adm'
    | '/membros'
    | '/produtor'
    | '/produtor/curso/$id'
    | '/produtor/editar/$id'
    | '/produtor/sucesso/$id'
    | '/api/public/webhooks/multicaixa'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contactos'
    | '/faq'
    | '/legends'
    | '/loja'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/_authenticated/adm'
    | '/_authenticated/afiliados'
    | '/_authenticated/perfil'
    | '/_authenticated/produtor'
    | '/checkout/$slug'
    | '/p/$slug'
    | '/pedido/$token'
    | '/produto/$slug'
    | '/_authenticated/adm/logs'
    | '/_authenticated/adm/produtos'
    | '/_authenticated/adm/relatorios'
    | '/_authenticated/adm/saques'
    | '/_authenticated/adm/usuarios'
    | '/_authenticated/membros/$slug'
    | '/_authenticated/produtor/conquistas'
    | '/_authenticated/produtor/financeiro'
    | '/_authenticated/produtor/funil'
    | '/_authenticated/produtor/integracoes'
    | '/_authenticated/produtor/novo'
    | '/_authenticated/produtor/produtos'
    | '/_authenticated/produtor/saques'
    | '/_authenticated/adm/'
    | '/_authenticated/membros/'
    | '/_authenticated/produtor/'
    | '/_authenticated/produtor/curso/$id'
    | '/_authenticated/produtor/editar/$id'
    | '/_authenticated/produtor/sucesso/$id'
    | '/api/public/webhooks/multicaixa'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactosRoute: typeof ContactosRoute
  FaqRoute: typeof FaqRoute
  LegendsRoute: typeof LegendsRoute
  LojaRoute: typeof LojaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  PSlugRoute: typeof PSlugRoute
  PedidoTokenRoute: typeof PedidoTokenRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicWebhooksMulticaixaRoute: typeof ApiPublicWebhooksMulticaixaRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legends': {
      id: '/legends'
      path: '/legends'
      fullPath: '/legends'
      preLoaderRoute: typeof LegendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$token': {
      id: '/pedido/$token'
      path: '/pedido/$token'
      fullPath: '/pedido/$token'
      preLoaderRoute: typeof PedidoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/produtor': {
      id: '/_authenticated/produtor'
      path: '/produtor'
      fullPath: '/produtor'
      preLoaderRoute: typeof AuthenticatedProdutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/afiliados': {
      id: '/_authenticated/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AuthenticatedAfiliadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adm': {
      id: '/_authenticated/adm'
      path: '/adm'
      fullPath: '/adm'
      preLoaderRoute: typeof AuthenticatedAdmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtor/': {
      id: '/_authenticated/produtor/'
      path: '/'
      fullPath: '/produtor/'
      preLoaderRoute: typeof AuthenticatedProdutorIndexRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/membros/': {
      id: '/_authenticated/membros/'
      path: '/membros'
      fullPath: '/membros/'
      preLoaderRoute: typeof AuthenticatedMembrosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adm/': {
      id: '/_authenticated/adm/'
      path: '/'
      fullPath: '/adm/'
      preLoaderRoute: typeof AuthenticatedAdmIndexRouteImport
      parentRoute: typeof AuthenticatedAdmRoute
    }
    '/_authenticated/produtor/saques': {
      id: '/_authenticated/produtor/saques'
      path: '/saques'
      fullPath: '/produtor/saques'
      preLoaderRoute: typeof AuthenticatedProdutorSaquesRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/produtor/produtos': {
      id: '/_authenticated/produtor/produtos'
      path: '/produtos'
      fullPath: '/produtor/produtos'
      preLoaderRoute: typeof AuthenticatedProdutorProdutosRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/produtor/novo': {
      id: '/_authenticated/produtor/novo'
      path: '/novo'
      fullPath: '/produtor/novo'
      preLoaderRoute: typeof AuthenticatedProdutorNovoRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/produtor/integracoes': {
      id: '/_authenticated/produtor/integracoes'
      path: '/integracoes'
      fullPath: '/produtor/integracoes'
      preLoaderRoute: typeof AuthenticatedProdutorIntegracoesRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/produtor/funil': {
      id: '/_authenticated/produtor/funil'
      path: '/funil'
      fullPath: '/produtor/funil'
      preLoaderRoute: typeof AuthenticatedProdutorFunilRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/produtor/financeiro': {
      id: '/_authenticated/produtor/financeiro'
      path: '/financeiro'
      fullPath: '/produtor/financeiro'
      preLoaderRoute: typeof AuthenticatedProdutorFinanceiroRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/produtor/conquistas': {
      id: '/_authenticated/produtor/conquistas'
      path: '/conquistas'
      fullPath: '/produtor/conquistas'
      preLoaderRoute: typeof AuthenticatedProdutorConquistasRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/membros/$slug': {
      id: '/_authenticated/membros/$slug'
      path: '/membros/$slug'
      fullPath: '/membros/$slug'
      preLoaderRoute: typeof AuthenticatedMembrosSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adm/usuarios': {
      id: '/_authenticated/adm/usuarios'
      path: '/usuarios'
      fullPath: '/adm/usuarios'
      preLoaderRoute: typeof AuthenticatedAdmUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdmRoute
    }
    '/_authenticated/adm/saques': {
      id: '/_authenticated/adm/saques'
      path: '/saques'
      fullPath: '/adm/saques'
      preLoaderRoute: typeof AuthenticatedAdmSaquesRouteImport
      parentRoute: typeof AuthenticatedAdmRoute
    }
    '/_authenticated/adm/relatorios': {
      id: '/_authenticated/adm/relatorios'
      path: '/relatorios'
      fullPath: '/adm/relatorios'
      preLoaderRoute: typeof AuthenticatedAdmRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdmRoute
    }
    '/_authenticated/adm/produtos': {
      id: '/_authenticated/adm/produtos'
      path: '/produtos'
      fullPath: '/adm/produtos'
      preLoaderRoute: typeof AuthenticatedAdmProdutosRouteImport
      parentRoute: typeof AuthenticatedAdmRoute
    }
    '/_authenticated/adm/logs': {
      id: '/_authenticated/adm/logs'
      path: '/logs'
      fullPath: '/adm/logs'
      preLoaderRoute: typeof AuthenticatedAdmLogsRouteImport
      parentRoute: typeof AuthenticatedAdmRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/multicaixa': {
      id: '/api/public/webhooks/multicaixa'
      path: '/api/public/webhooks/multicaixa'
      fullPath: '/api/public/webhooks/multicaixa'
      preLoaderRoute: typeof ApiPublicWebhooksMulticaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/produtor/sucesso/$id': {
      id: '/_authenticated/produtor/sucesso/$id'
      path: '/sucesso/$id'
      fullPath: '/produtor/sucesso/$id'
      preLoaderRoute: typeof AuthenticatedProdutorSucessoIdRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/produtor/editar/$id': {
      id: '/_authenticated/produtor/editar/$id'
      path: '/editar/$id'
      fullPath: '/produtor/editar/$id'
      preLoaderRoute: typeof AuthenticatedProdutorEditarIdRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/produtor/curso/$id': {
      id: '/_authenticated/produtor/curso/$id'
      path: '/curso/$id'
      fullPath: '/produtor/curso/$id'
      preLoaderRoute: typeof AuthenticatedProdutorCursoIdRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
  }
}

interface AuthenticatedAdmRouteChildren {
  AuthenticatedAdmLogsRoute: typeof AuthenticatedAdmLogsRoute
  AuthenticatedAdmProdutosRoute: typeof AuthenticatedAdmProdutosRoute
  AuthenticatedAdmRelatoriosRoute: typeof AuthenticatedAdmRelatoriosRoute
  AuthenticatedAdmSaquesRoute: typeof AuthenticatedAdmSaquesRoute
  AuthenticatedAdmUsuariosRoute: typeof AuthenticatedAdmUsuariosRoute
  AuthenticatedAdmIndexRoute: typeof AuthenticatedAdmIndexRoute
}

const AuthenticatedAdmRouteChildren: AuthenticatedAdmRouteChildren = {
  AuthenticatedAdmLogsRoute: AuthenticatedAdmLogsRoute,
  AuthenticatedAdmProdutosRoute: AuthenticatedAdmProdutosRoute,
  AuthenticatedAdmRelatoriosRoute: AuthenticatedAdmRelatoriosRoute,
  AuthenticatedAdmSaquesRoute: AuthenticatedAdmSaquesRoute,
  AuthenticatedAdmUsuariosRoute: AuthenticatedAdmUsuariosRoute,
  AuthenticatedAdmIndexRoute: AuthenticatedAdmIndexRoute,
}

const AuthenticatedAdmRouteWithChildren =
  AuthenticatedAdmRoute._addFileChildren(AuthenticatedAdmRouteChildren)

interface AuthenticatedProdutorRouteChildren {
  AuthenticatedProdutorConquistasRoute: typeof AuthenticatedProdutorConquistasRoute
  AuthenticatedProdutorFinanceiroRoute: typeof AuthenticatedProdutorFinanceiroRoute
  AuthenticatedProdutorFunilRoute: typeof AuthenticatedProdutorFunilRoute
  AuthenticatedProdutorIntegracoesRoute: typeof AuthenticatedProdutorIntegracoesRoute
  AuthenticatedProdutorNovoRoute: typeof AuthenticatedProdutorNovoRoute
  AuthenticatedProdutorProdutosRoute: typeof AuthenticatedProdutorProdutosRoute
  AuthenticatedProdutorSaquesRoute: typeof AuthenticatedProdutorSaquesRoute
  AuthenticatedProdutorIndexRoute: typeof AuthenticatedProdutorIndexRoute
  AuthenticatedProdutorCursoIdRoute: typeof AuthenticatedProdutorCursoIdRoute
  AuthenticatedProdutorEditarIdRoute: typeof AuthenticatedProdutorEditarIdRoute
  AuthenticatedProdutorSucessoIdRoute: typeof AuthenticatedProdutorSucessoIdRoute
}

const AuthenticatedProdutorRouteChildren: AuthenticatedProdutorRouteChildren = {
  AuthenticatedProdutorConquistasRoute: AuthenticatedProdutorConquistasRoute,
  AuthenticatedProdutorFinanceiroRoute: AuthenticatedProdutorFinanceiroRoute,
  AuthenticatedProdutorFunilRoute: AuthenticatedProdutorFunilRoute,
  AuthenticatedProdutorIntegracoesRoute: AuthenticatedProdutorIntegracoesRoute,
  AuthenticatedProdutorNovoRoute: AuthenticatedProdutorNovoRoute,
  AuthenticatedProdutorProdutosRoute: AuthenticatedProdutorProdutosRoute,
  AuthenticatedProdutorSaquesRoute: AuthenticatedProdutorSaquesRoute,
  AuthenticatedProdutorIndexRoute: AuthenticatedProdutorIndexRoute,
  AuthenticatedProdutorCursoIdRoute: AuthenticatedProdutorCursoIdRoute,
  AuthenticatedProdutorEditarIdRoute: AuthenticatedProdutorEditarIdRoute,
  AuthenticatedProdutorSucessoIdRoute: AuthenticatedProdutorSucessoIdRoute,
}

const AuthenticatedProdutorRouteWithChildren =
  AuthenticatedProdutorRoute._addFileChildren(
    AuthenticatedProdutorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdmRoute: typeof AuthenticatedAdmRouteWithChildren
  AuthenticatedAfiliadosRoute: typeof AuthenticatedAfiliadosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProdutorRoute: typeof AuthenticatedProdutorRouteWithChildren
  AuthenticatedMembrosSlugRoute: typeof AuthenticatedMembrosSlugRoute
  AuthenticatedMembrosIndexRoute: typeof AuthenticatedMembrosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdmRoute: AuthenticatedAdmRouteWithChildren,
  AuthenticatedAfiliadosRoute: AuthenticatedAfiliadosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProdutorRoute: AuthenticatedProdutorRouteWithChildren,
  AuthenticatedMembrosSlugRoute: AuthenticatedMembrosSlugRoute,
  AuthenticatedMembrosIndexRoute: AuthenticatedMembrosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactosRoute: ContactosRoute,
  FaqRoute: FaqRoute,
  LegendsRoute: LegendsRoute,
  LojaRoute: LojaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  PSlugRoute: PSlugRoute,
  PedidoTokenRoute: PedidoTokenRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicWebhooksMulticaixaRoute: ApiPublicWebhooksMulticaixaRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
